### ISSUE TITLE
[Epic] Project Setup

### ISSUE THREAD

**Issue by ocallarob** [ocallarob/scrudu#1]
Basic End to End flow to get the project off the ground.

Requirements for the Walking Skeleton are the following:

- [x] It should be run automated testing
- [x] It should be runnable from the command line
- [x] It should be able to read project files (.spec.js)
- [x] It should be able to create/write project files (README.md)
